<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><GameDir Condition="'$(GameDir)' == ''">D:\SteamLibrary\steamapps\common\Go Next! Demo</GameDir></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/GoNextCoreRepair/CoreRepair.cs" Link="CoreRepair.cs" />
    <Reference Include="Mono.Cecil"><HintPath>$(GameDir)\MelonLoader\net6\Mono.Cecil.dll</HintPath></Reference>
  </ItemGroup>
</Project>
